### ISSUE TITLE
Allow modification of episode title for file name

### ISSUE THREAD

**Issue by BitScout** [BitScout/podarchiver#7]
Add configuration root entry `title_modifiers` where multiple replacement pattern sets can be configured so they can be applied to episode titles.

```
title_modifiers:
    - foo:
        regex: /(.*)/
        output: $1
    - bar:
        ...
feeds:
    Fubar:
        ...
        title_modifiers:
            - foo
            - bar
```
